apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app-pod

spec:
  containers:
    - name: two-tier-app-ctr
      image: thisisyatingarg/flaskapp:latest
      ports:
        - containerPort: 5000
      imagePullPolicy: Always
      env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_DB
          value: "mydb"
