apiVersion: v1
kind: Service
metadata:
  name: two-tier-app-svc
  
spec:
  selector:
    app: two-tier-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30017  
